# Tutorial 14:

In [3]:
import numpy as np

**COPY V/S VIEW:**

In [11]:
array_1 = np.array([1,2,3,4])
copy_1 = array_1.copy()
copy_1[0] = 16
print(array_1)
print(copy_1)

[1 2 3 4]
[16  2  3  4]


In [12]:
array_2 = np.array([1,2,3,4])
view_1 = array_2.view()
view_1[0] = 16
print(array_2)
print(view_1)

[16  2  3  4]
[16  2  3  4]
