# Tutorial 5:

**RAND() FUNCTION**

In [3]:
import numpy as np
array_rand = np.random.rand(5)
print(array_rand)

[0.61229032 0.50412801 0.25421262 0.14899734 0.93334677]


In [4]:
array_rand_1 = np.random.rand(2,5)
print(array_rand_1)

[[0.21430143 0.44696202 0.81383895 0.20278105 0.76681887]
 [0.59818243 0.34005978 0.2284344  0.02601219 0.3190065 ]]


**RANDN() FUNCTION**

In [5]:
array_randn = np.random.randn(5)
print(array_randn)

[-0.86232622 -1.20397097  1.66778159  0.85034909  2.12634474]


In [6]:
array_randn_1 = np.random.randn(5,4)
print(array_randn_1)

[[-0.08169748 -0.01998109 -2.29469524 -0.51046678]
 [ 0.021815    0.32507404  1.30951478 -0.34912813]
 [-1.33941663  0.55620174 -1.91410408  0.21760156]
 [-1.68366319  0.80154625 -1.16116435  1.69765351]
 [-0.79871372 -2.29839243 -0.07826436 -0.04184489]]


**RANF() FUNCTION**

In [7]:
array_ranf = np.random.ranf(4)
print(array_ranf)

[0.30438023 0.58595308 0.49932141 0.79795365]


In [11]:
array_ranf_1 = np.random.ranf(3)
print(array_ranf_1)

[0.18111003 0.45974415 0.73646372]


**RANDINT() FUNCTION**

In [15]:
array_randint = np.random.randint(1,20,5)
print(array_randint)

[ 9  1  9 12  1]
