# Tutorial 18:

**MATRIX IN NUMPY ARRAYS:**

In [2]:
import numpy as np

In [25]:
var = np.matrix([[1,2,3],[1,2,3]])
var_0 = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print("addition = \n",var+var_0)
print("subtraction = \n",var-var_0)
print("multiplication(dot) = \n",var.dot(var_0))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

addition = 
 [[2 4 6]
 [2 4 6]]
subtraction = 
 [[0 0 0]
 [0 0 0]]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [23]:
var_1 = np.array([[1,2,3],[1,2,3]])
var_01 = np.array([[1,2,3],[1,2,3]])
print(var_1)
print(type(var_1))
print()
print("addition = \n",var_1+var_01)
print("subtraction = \n",var_1-var_01)
print("multiplication = \n",var_1*var_01)

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

addition = 
 [[2 4 6]
 [2 4 6]]
subtraction = 
 [[0 0 0]
 [0 0 0]]
multiplication = 
 [[1 4 9]
 [1 4 9]]


**TRANSPOSE FUNCTION:**

In [27]:
m_1 = np.matrix([[1,2,3],[4,5,6]])
print(m_1)
print()
print(np.transpose(m_1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


**SWAPAXES FUNCTION:**

In [28]:
m_1 = np.matrix([[1,2,3],[4,5,6]])
print(m_1)
print()
print(np.swapaxes(m_1,0,1))

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [30]:
m_2 = np.matrix([[1,2],[3,4]])
print(np.swapaxes(m_2,0,1))

[[1 3]
 [2 4]]


In [32]:
m_2 = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(m_2))

[[-2.   1. ]
 [ 1.5 -0.5]]


**POWER FUNCTION:**

In [38]:
m_3 = np.matrix([[1,2],[3,4]])
print(m_3)
print()
print(np.linalg.matrix_power(m_3,2))
print(np.linalg.matrix_power(m_3,0))     
print(np.linalg.matrix_power(m_3,-2))     

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]


**DETERMINANT FUNCTION():**

In [41]:
m_3 = np.matrix([[1,2,4],[3,4,6],[6,0,6]])
print(m_3)
print()
print(np.linalg.det(m_3))

[[1 2 4]
 [3 4 6]
 [6 0 6]]

-36.0
