# Tutorial 11:

**INDEXING IN NUMPY ARRAYS:**

In [1]:
import numpy as np
array_1 = np.array([9,8,7,6]) # 1D array
print(array_1[1])
print(array_1[-1])
print(array_1[-2])

8
6
7


In [2]:
array_2 = np.array([[9,8,7],[1,2,3]]) # 2D array
print(array_2[0])
print(array_2[0][1])
print(array_2[1])
print(array_2[1][0])


[9 8 7]
8
[1 2 3]
1


In [14]:
array_3 = np.array([[[1,2],[3,4]],[[9,10],[5,6]]]) # 3D array
print(array_3[0])
print(array_3[0][1])
print(array_3[0,1,0]) # Also, print(array_3[0][1][0])
print(array_3[1])

[[1 2]
 [3 4]]
[3 4]
3
[[ 9 10]
 [ 5  6]]


**SLICING IN NUMPY ARRAYS:**

In [8]:
array_4 = np.array([1,2,3,4,5,6,7,8,9]) # 1D array
print(array_4[1:4])
print(array_4[2:])
print(array_4[:3])
print(array_4[:])
print(array_4[0:8:2])
print(array_4[::-1])

[2 3 4]
[3 4 5 6 7 8 9]
[1 2 3]
[1 2 3 4 5 6 7 8 9]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1]


In [16]:
array_5 = np.array([[1,2,3,4],[3,4,5,6],[6,7,1,2],[9,2,5,4]]) # 2D array
print(array_5[1:])
print(array_5[0][1:]) # Also, print(array_5[0,1:])
print(array_5[1,:])

[[3 4 5 6]
 [6 7 1 2]
 [9 2 5 4]]
[2 3 4]
[3 4 5 6]
