# Tutorial 15:

**JOINING ARRAYS (USING, .CONCATENATE() AND .STACK()):**

In [13]:
import numpy as np
ar_1 = np.array([1,2,3,4])
ar_2 = np.array([4,5,6,7])
# var = np.concatenate((ar_1,ar_2),axis = 1) # For this we can use '.stack()' method
var = np.stack((ar_1,ar_2),axis = 1) # For this we can use '.stack()' method
ar_1 = np.concatenate((ar_1,ar_2))
print(ar_1)
print(var)

[1 2 3 4 4 5 6 7]
[[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [12]:
ar_1 = np.array([[1,2,3],[4,5,6]])
ar_2 = np.array([[3,3,4],[9,6,6]])
var = np.concatenate((ar_1,ar_2)) # axis = 0
var_1 = np.concatenate((ar_1,ar_2),axis = 1)
print(var)
print(var_1)

[[1 2 3]
 [4 5 6]
 [3 3 4]
 [9 6 6]]
[[1 2 3 3 3 4]
 [4 5 6 9 6 6]]


In [10]:
arr_1 = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]])
arr_2 = np.array([[[3,3,4],[9,6,6]],[[3,3,3],[7,8,9]]])
var_3 = np.concatenate((arr_1,arr_2)) # axis = 0
var_4 = np.concatenate((arr_1,arr_2),axis = 1)
print(var_3)
print(var_4)

[[[1 2 3]
  [4 5 6]]

 [[1 1 1]
  [2 2 2]]

 [[3 3 4]
  [9 6 6]]

 [[3 3 3]
  [7 8 9]]]
[[[1 2 3]
  [4 5 6]
  [3 3 4]
  [9 6 6]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]
  [7 8 9]]]


In [16]:
a_1 = np.array([1,2,3])
a_2 = np.array([4,5,6])
v_1  = np.stack((a_1,a_2),axis = 1)
v_2  = np.hstack((a_1,a_2)) # Works along row
v_3  = np.vstack((a_1,a_2)) # Works along column
v_4  = np.dstack((a_1,a_2)) # Works alonh height
print(v_1)
print()
print(v_2)
print()
print(v_3)
print()
print(v_4)

[[1 4]
 [2 5]
 [3 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]]


**SPLITTING ARRAYS(USING .SPLIT()):**

In [26]:
v_1 = np.array([1,2,3,4,5,6])
s_1 = np.split(v_1,2)
s_2 = np.array_split(v_1,2)
print(v_1)
print(s_1)
print(s_2)
print(s_2[0])

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[1 2 3]


In [37]:
v_1 = np.array([[1,2,3,4,5,6],[4,5,6,7,8,9]])
s_1 = np.split(v_1,2)
s_2 = np.array_split(v_1,2)
s_3 = np.array_split(v_1,2,axis =1)
print(v_1)
print(s_1)
print(s_2)
print(s_2[0])
print(s_3)

[[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 8, 9]])]
[array([[1, 2, 3, 4, 5, 6]]), array([[4, 5, 6, 7, 8, 9]])]
[[1 2 3 4 5 6]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[4, 5, 6],
       [7, 8, 9]])]
