# Tutorial 9:

**SHAPES IN NUMPY ARRAYS:**

In [11]:
import numpy as np
array = np.array([[1,2],[3,4]]) # 2x2 matrix
array_1 = np.array([[1,2],[3,4],[5,6]]) # 3x2 matrix
print(array)
print()
print(array.shape)
print("Shape is : ",array_1.shape)

[[1 2]
 [3 4]]

(2, 2)
Shape is :  (3, 2)


In [10]:
array_2 = np.array([1,2,3,4],ndmin = 4)
print(array_2)
print(array_2.ndim)
print("Shape is : ",array_2.shape)

[[[[1 2 3 4]]]]
4
Shape is :  (1, 1, 1, 4)


**RESHAPE IN NUMPY ARRAY:**

In [21]:
array_3 = np.array([1,2,3,4,5,6])
print("1D array is : ",array_3)
print("Dimension is : ",array_3.ndim)
reshaping = array_3.reshape(3,2) # If no sufficient elements for the row than error occurs
print("2D array is : \n",reshaping)
print("Dimension is : ",reshaping.ndim)
print("Shape is : ",reshaping.shape)

1D array is :  [1 2 3 4 5 6]
Dimension is :  1
2D array is : 
 [[1 2]
 [3 4]
 [5 6]]
Dimension is :  2
Shape is :  (3, 2)


In [27]:
array_4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# Total elements = 2*3*2 = 12
reshaping = array_4.reshape(2,3,2) # 3D array of two rows containing 2 rows and 3 column 
print(reshaping)
print("\nDimension is : ",reshaping.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

Dimension is :  3


In [30]:
array_4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaping = array_4.reshape(2,3,2) # 3D array of two rows containing 2 rows and 3 column 
again_reshape = reshaping.reshape(-1) # Use reshape(-1) to reshape to 1D Array
print(again_reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
