# Tutorial 16:

**SEARCH ARRAY (.WHERE()):**

In [8]:
import numpy as np
arr_1 = np.array([1,2,3,4,4,5,2,2,2])
where_1 = np.where(arr_1 == 2)
print(where_1)


(array([1, 6, 7, 8]),)


**SEARCH SORTED ARRAY (SEARCHSORTED()):**

In [21]:
arr_2 = np.array([1,2,3,4,6])
ss = np.searchsorted(arr_2 , 6 )
ss_1 = np.searchsorted(arr_2 , 6 , side = "right")
ss_3 = np.searchsorted(arr_2 , [6,7,8] , side = "right")
print(ss)
print(ss_1)
print(ss_3)

4
5
[5 5 5]


**SORT ARRAY(.SORT()):**

In [23]:
ar = np.array([3,5,8,1,2,6,"a","A"])
sort = np.sort(ar)
print(sort)

['1' '2' '3' '5' '6' '8' 'A' 'a']


In [25]:
ar_1 = np.array([[3,1,2],[4,8,7]])
print(np.sort(ar_1))

[[1 2 3]
 [4 7 8]]


**FILTER ARRAY(arr_1 [ f ] ):**

In [31]:
ar_2 = np.array([3,4,7,6,5])
f = [True,False,True,False,True]
print(ar_2[f])

[3 7 5]


**SHUFFLE ARRAY (RANDOM.SHUFFLE):**

In [32]:
a_1 = np.array([1,2,3,4,5])
np.random.shuffle(a_1)
print(a_1)

[3 1 4 5 2]


**UNIQUE ARRAY ():

In [37]:
a_2 = np.array([1,2,3,4,5,4,3,7,8])
print(np.unique(a_2))
print(np.unique(a_2,return_index = True,return_counts = True))

[1 2 3 4 5 7 8]
(array([1, 2, 3, 4, 5, 7, 8]), array([0, 1, 2, 3, 4, 7, 8]), array([1, 1, 2, 2, 1, 1, 1]))


**RESIZE ARRAY (.RESIZE()):**

In [41]:
a_3 = np.array([1,2,3,4,5,6,7])
print(np.resize(a_3,(2,9)))

[[1 2 3 4 5 6 7 1 2]
 [3 4 5 6 7 1 2 3 4]]


**FLATTEN ARRAY (.FLATTEN()):**

In [47]:
a_4 = np.array([[1,2,3],[4,5,6]])
print(a_4.flatten())
print(a_4.flatten(order = "C"))
print()
print(a_4.flatten(order = "A"))
print()
print(a_4.flatten(order = "K"))
print()
print(a_4.flatten(order = "F"))
print()

[1 2 3 4 5 6]
[1 2 3 4 5 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]

[1 4 2 5 3 6]



**RAVEL ARRAY (.RAVEL()):**

In [51]:
a_5 = np.array([[1,2,3],[4,5,6]])
print(a_5)
print()
print(np.ravel(a_5,order = "F"))

[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]
